routes/web.php
<?php


Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    
    Route::get('/', 'HomeController@index');
    // Route::get('categories', function () {
    //     return view('categorys.category');
    // });

    Route::group(['middleware' => ['admin']], function () {
        Route::resources([
            'categories' => 'CategoryController', 
            'membercat' => 'CategorysController',
        ]);
    });

    Route::resources([
        'products' => 'ProductController',
        'promos' => 'PromosController',
        'transactions' => 'TransaksiController',
        'members' => 'MemberController',
    ]);    

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Product.php
<?php

// namespace App;

// use Illuminate\Database\Eloquent\Model;

// class Product extends Model
// {
//     protected $guarded =['id'];
//     protected $fillable = ['name','image','product_category_id','desc','amount'];
//     public function product()
//     {
//         return $this->belonggsTo(Category::class, 'product_category_id'); 
//     }
// }

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Category;
use App\table_product;
use DB;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        
        $products = table_product::all();
        $categories = Category::all();
        return view('product.produc', compact('products', 'categories'));
    }
    public function store(Request $request)
    {
        $request->validate([
            'name'  =>  'required',
            'desc'  =>  'required',
            'amount' => 'required',
            'product_category_id'  =>  'required',
            'image'  =>  'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        if ($request->has('active')) {
           $active = 1;
        } else {
            $active = 0;
        }

        $fileName = str_replace("=","",base64_encode($request->name.time())) . '.' . request()->image->getClientOriginalExtension();

        if(!$request->image->move(storage_path('app/public/promo'), $fileName)){
            return array('error' => 'Gagal upload foto');
        } else {
            $product = new table_product ();
            $product->name = $request->name;
            $product->desc = $request->desc;
            $product->amount = $request->amount;
            $product->product_category_id = $request->product_category_id;
            $product->image = "storage/promo/".$fileName;;
            $product->save();
        }

        return redirect('/');
       
    }
    public function destroy(table_product $product)
    {
        $product->delete();

        return back();
    }
    public function edit(table_product $product)
    {
        $categories = Category::all();
        return view('product.edits' , compact('categories','product'));
    }
    public function update(Request $request, $id)
    {
        $productPict = table_product::where("id","=",$id)->get()->first()->image;
        // return response()->json($productPict);
        if (!$request->image) {
            $request->validate([
                'name'  =>  'required',
                'product_category_id'  =>  'required',
                'desc'  =>  'required',
                'amount' => 'required',
            ]);
        } else {
            // return 'changed';
            $request->validate([
                'name'  =>  'required',
                'product_category_id'  =>  'required',
                'desc'  =>  'required',
                'image'  =>  'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'amount' => 'required',
            ]);
            $fileName = str_replace("=","",base64_encode($request->name.time())) . '.' . request()->image->getClientOriginalExtension();
        }

        if ($request->has('active')) {
            $active = 1;
         } else {
             $active = 0;
         }

        $product = table_product::findOrFail($id);
        $product->name = $request->name;
        $product->desc = $request->desc;
        $product->product_category_id = $request->product_category_id;
        $product->amount  = $request->amount;
        if($request->hasFile('image')){
            // return 'has file';
            if (is_file($product->image)) {
                try {
                    unlink($productPict);
                } catch(\Exception $e) {

                }
            }
            $request->image->move(storage_path('app/public/promo'), $fileName);
            $product->image = "storage/promo/".$fileName;
        }else {
            // return 'kosong';
            $product->image = $productPict;
        }
        $product->save();

        return redirect("/");
    }
   
}

resources/views/product/edits.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Edit Product
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="{{ route('products.update', $product->id) }}" method="post" autocomplete="off" class="form-group">
                        @csrf
                        @method('PUT')
                                <div class="form-group">
                                  <label for="name">name</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="name" id="name" value="{{ $product->name }}">
                                  {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                                  <div class="fallback">
                                        <label>Upload Photo</label>
                                        <input type="file" id="image" name="image" class="form_control"  value="{{ $product->image }}">
                                  </div>
                                  <br>                                 
                                  <div class="form-group">
                                  <label for="product_category_id">category</label>
                                  <div class="form-line">
                                  <select  class="form-control" name="product_category_id" id="product_category_id">
                                    <option disabled selected>Pilih Satu</option>
                                    @foreach($categories as $cats)
                                        <option {{ $product->product_category_id == $cats->id ? "selected" : ""}} value="{{ $cats->id }}"> {{ $cats->name }} </option>
                                    @endforeach
                                   </select> 
                                  </div>
                                  </div>
                                  <div class="form-group">
                                  <label for="desc">desc</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="desc" id="desc" value="{{ $product->desc }}">
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                                  <div class="form-group">
                                  <label for="amount">amount</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="amount" id="amount" value="{{ $product->amount }}">
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                            <button type="submit" class="btn btn-primary">update</button>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection

resources/views/product/produc.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Input Product
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="{{ route('products.store') }}" method="post" autocomplete="off" class="form-group" enctype="multipart/form-data">
                        @csrf
                                <div class="form-group">
                                  <label for="name">name</label>
                                    <div class="form-line">
                                        <input type="text" class="form-control" name="name" id="name">
                                        {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <div class="fallback">
                                        <label>Upload Photo</label>
                                        <input type="file" id="image" name="image" class="form_control">
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <label for="product_category_id">category</label>
                                    <div class="form-line">
                                        <select  class="form-control" name="product_category_id" id="product_category_id">
                                            <option disabled selected>Pilih Satu</option>
                                            @foreach($categories as $cats)
                                                <option value="{{ $cats->id }}"> {{ $cats->name }} </option>
                                            @endforeach
                                        </select> 
                                    </div>
                                  </div>
                                  <div class="form-group">
                                  <label for="desc">desc</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="desc" id="desc">
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div></div>
                                  <div class="form-group">
                                  <label for="amount">amount</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="amount" id="amount">
                                  {!! $errors->first('amount', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                            <button type="submit" class="btn btn-primary">simpan</button>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection