routes/web.php
<?php


Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    
    Route::get('/', 'HomeController@index');
    // Route::get('categories', function () {
    //     return view('categorys.category');
    // });

    Route::group(['middleware' => ['admin']], function () {
        Route::resources([
            'categories' => 'CategoryController', 
            'membercat' => 'CategorysController',
        ]);
    });

    Route::resources([
        'products' => 'ProductController',
        'promos' => 'PromosController',
        'transactions' => 'TransaksiController',
        'members' => 'MemberController',
    ]);    

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable=['name','desc'];
}

app/Categorys.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorys extends Model
{
    public function members()
    {
        return $this->hasMany(Member::class, 'member_category_id'); 
    }
    protected $table = 'member_categories';

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;
use App\Category;
use Illuminate\Http\Request;


class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('categorys.category', compact('category', 'categories'));
    }
    public function store()
    {
        $categories = new Category();   
        $categories->name = request('name');
        $categories->desc = request('desc');
        $categories->save();

        return redirect('/');
       
    }
    public function destroy(Category $categories , $id )
    {
        $categories = Category::findOrFail($id);
        $categories->delete();

        return back();
    }
    public function edit(Category $category)
    {
        
        return view('categorys.edite' , compact('category'));
    }
    public function update(Request $request, Category $categories, $id)
    {
      
        $request->validate([
            'name' => 'required',
            'desc' => 'required',

    
            ]);
        $categories = Category::findOrFail($id);
        $categories->name = $request->name;
        $categories->desc =  $request->desc;
        $categories->update();
            // $categories->save();
        
       
        return redirect("/");
    }

}

app/Http/Controllers/CategorysController.php
<?php

namespace App\Http\Controllers;
use\App\Categorys;
use Illuminate\Http\Request;

class CategorysController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $membercat = Categorys::all();
       return view('membercat.index', compact('membercat'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $membercat = new Categorys();   
        $membercat->name = request('name');
        $membercat->save();

        return redirect('/membercat');
           }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Categorys $membercat)
    {
        return view('membercat.edit' , compact('membercat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categorys $categorys, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $data = Categorys::findOrFail($id);
        $data->name = $request->name;
        $data->update();
        //    return response()->json($data);

        return redirect('membercat');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categorys $categorys, $id)
    {
        $category = $categorys::findOrFail($id);
        $category->delete();
        return redirect('membercat');   
    }
}

resources/views/categorys/category.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Product Category
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="{{ route('categories.store') }}" method="post" autocomplete="off" class="form-group">
                        @csrf
                                <div class="form-group">
                                  <label for="name">name</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="name" id="name">
                                  {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>

                                <div class="form-group">
                                  <label for="desc">desc</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="desc" id="desc">
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                            <button type="submit" class="btn btn-primary">simpan</button>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection

resources/views/categorys/edite.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Product Category
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="{{ route('categories.update', $category->id) }}" method="post" autocomplete="off" class="form-group">
                        @csrf
                        @method('PUT')
                                <div class="form-group">
                                  <label for="name">name</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="name" id="name" value="{{ $category->name }}">
                                  {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>

                                <div class="form-group">
                                  <label for="desc">desc</label>
                                  <div class="form-line">
                                  <input type="text" class="form-control" name="desc" id="desc" value="{{ $category->desc }}">
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                            <button type="submit" class="btn btn-primary">update</button>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection